

from graphviz import Digraph

taxonomy = Digraph(comment='Literature Review Taxonomy', engine='twopi')

taxonomy.attr(overlap='false')
taxonomy.attr(sep='0.5')
taxonomy.attr(nodesep='0.5')
taxonomy.attr(fontsize='20')
taxonomy.attr('node', fontname='Helvetica-Bold')

taxonomy.node('LiteratureReview', 'Literature Review', shape='ellipse', style='filled', fillcolor='lightblue')
taxonomy.node('GNNs', 'Graph Neural Networks (GNNs)', shape='ellipse', style='filled', fillcolor='lightblue')
taxonomy.node('DigitalTwins', 'Digital Twins', shape='ellipse', style='filled', fillcolor='lightblue')
taxonomy.node('ZeroTouchNetworks', 'O-RAN Zero-Touch Networks', shape='ellipse', style='filled', fillcolor='lightblue')

taxonomy.node('GNNIntro', 'Introduction', shape='rect', style='filled', fillcolor='lightblue')
taxonomy.node('GNNArchitecture', 'Architecture', shape='rect', style='filled', fillcolor='lightblue')
taxonomy.node('GNNKeyFeatures', 'Key features and benefits', shape='rect', style='filled', fillcolor='lightblue')
taxonomy.node('GNNApplications', 'Applications', shape='rect', style='filled', fillcolor='lightblue')
taxonomy.node('GNNLimitations', 'Limitations and challenges', shape='rect', style='filled', fillcolor='lightblue')
taxonomy.node('DTIntro', 'Introduction', shape='rect', style='filled', fillcolor='lightblue')
taxonomy.node('DTArchitecture', 'Architecture', shape='rect', style='filled', fillcolor='lightblue')
taxonomy.node('DTKeyFeatures', 'Key features and benefits', shape='rect', style='filled', fillcolor='lightblue')
taxonomy.node('DTApplications', 'Applications', shape='rect', style='filled', fillcolor='lightblue')
taxonomy.node('DTLimitations', 'Limitations and challenges', shape='rect', style='filled', fillcolor='lightblue')
taxonomy.node('ZeroTouchIntro', 'Introduction', shape='rect', style='filled', fillcolor='lightblue')
taxonomy.node('ZeroTouchArchitecture', 'Architecture', shape='rect', style='filled', fillcolor='lightblue')
taxonomy.node('ZeroTouchKeyFeatures', 'Key features and benefits', shape='rect', style='filled', fillcolor='lightblue')
taxonomy.node('ZeroTouchApplications', 'Applications', shape='rect', style='filled', fillcolor='lightblue')
taxonomy.node('ZeroTouchLimitations', 'Limitations and challenges', shape='rect', style='filled', fillcolor='lightblue')

taxonomy.edge('LiteratureReview', 'GNNs')
taxonomy.edge('LiteratureReview', 'DigitalTwins')
taxonomy.edge('LiteratureReview', 'ZeroTouchNetworks')
taxonomy.edge('GNNs','GNNIntro')
taxonomy.edge('GNNs', 'GNNArchitecture')
taxonomy.edge('GNNs', 'GNNKeyFeatures')
taxonomy.edge('GNNs', 'GNNApplications')
taxonomy.edge('GNNs', 'GNNLimitations')
taxonomy.edge('DigitalTwins', 'DTIntro')
taxonomy.edge('DigitalTwins', 'DTArchitecture')
taxonomy.edge('DigitalTwins', 'DTKeyFeatures')
taxonomy.edge('DigitalTwins', 'DTApplications')
taxonomy.edge('DigitalTwins', 'DTLimitations')
taxonomy.edge('ZeroTouchNetworks', 'ZeroTouchIntro')
taxonomy.edge('ZeroTouchNetworks', 'ZeroTouchArchitecture')
taxonomy.edge('ZeroTouchNetworks', 'ZeroTouchKeyFeatures')
taxonomy.edge('ZeroTouchNetworks', 'ZeroTouchApplications')
taxonomy.edge('ZeroTouchNetworks', 'ZeroTouchLimitations')

taxonomy.render('taxonomy_LiteretureReview', format='png')
taxonomy.render('diagram1', format='png')
